import {
	ElAvatar,
	ElButton,
	ElDialog,
	ElDrawer,
	ElForm,
	ElFormItem,
	ElIcon,
	ElImage,
	ElInput,
	ElOption,
	ElSelect,
	ElSelectV2,
	ElTable,
	ElTableColumn,
	ElTree,
	ElTreeSelect,
	ElUpload,
} from "element-plus";
import elementPlusWebTypes from "element-plus/web-types.json";
import {
	FaAvatar,
	FaButton,
	FaCarNumber,
	FaContextMenu,
	FaDialog,
	FaDrawer,
	FaForm,
	FaFormItem,
	FaFormItemTip,
	FaIcon,
	FaIconSelector,
	FaImage,
	FaInputDialogPage,
	FaLayoutGrid,
	FaLayoutGridItem,
	FaSelect,
	FaSelectOption,
	FaSelectPage,
	FaSelectV2,
	FaTable,
	FaTableColumn,
	FaTree,
	FaTreeSelect,
	FaUpload,
	FaUploadImage,
	FaUploadImages,
} from "../../../../src";

const FaTableColumnsSettingDialog = FaTable.TableColumnsSettingDialog;
const FaTablePagination = FaTable.TablePagination;
const FaTableSearchForm = FaTable.TableSearchForm;
const FaTableSearchFormItem = FaTable.TableSearchFormItem;

export const fastComponents = {
	FaAvatar,
	FaButton,
	FaCarNumber,
	FaContextMenu,
	FaDialog,
	FaDrawer,
	FaForm,
	FaFormItem,
	FaFormItemTip,
	FaIcon,
	FaIconSelector,
	FaImage,
	FaInputDialogPage,
	FaLayoutGrid,
	FaLayoutGridItem,
	FaSelect,
	FaSelectOption,
	FaSelectPage,
	FaSelectV2,
	FaTable,
	FaTableColumn,
	FaTableColumnsSettingDialog,
	FaTablePagination,
	FaTableSearchForm,
	FaTableSearchFormItem,
	FaTree,
	FaTreeSelect,
	FaUpload,
	FaUploadImage,
	FaUploadImages,
} as const;

export const nativeComponents = {
	ElAvatar,
	ElButton,
	ElDialog,
	ElDrawer,
	ElForm,
	ElFormItem,
	ElIcon,
	ElImage,
	ElInput,
	ElOption,
	ElSelect,
	ElSelectV2,
	ElTable,
	ElTableColumn,
	ElTree,
	ElTreeSelect,
	ElUpload,
} as const;

export type FastComponentName = keyof typeof fastComponents;
export type NativeComponentName = keyof typeof nativeComponents;

export interface ComponentApiMetadata {
	changedProps?: string[];
	exposes?: string[];
	note?: string;
	slots?: string[];
}

export interface NativeApiMember {
	description?: string;
	name: string;
	type?: string;
}

export interface NativeApiDocumentation {
	events: NativeApiMember[];
	props: NativeApiMember[];
	slots: NativeApiMember[];
}

interface ElementPlusWebTypeMember {
	description?: string;
	name: string;
	type?: unknown;
}

interface ElementPlusWebTypeComponent {
	js?: { events?: ElementPlusWebTypeMember[] };
	name: string;
	props?: ElementPlusWebTypeMember[];
	slots?: ElementPlusWebTypeMember[];
}

interface ElementPlusWebTypes {
	contributions: {
		html: {
			"vue-components": ElementPlusWebTypeComponent[];
		};
	};
}

const nativeTagNames: Record<NativeComponentName, string> = {
	ElAvatar: "el-avatar",
	ElButton: "el-button",
	ElDialog: "el-dialog",
	ElDrawer: "el-drawer",
	ElForm: "el-form",
	ElFormItem: "el-form-item",
	ElIcon: "el-icon",
	ElImage: "el-image",
	ElInput: "el-input",
	ElOption: "el-option",
	ElSelect: "el-select",
	ElSelectV2: "el-virtualized-select",
	ElTable: "el-table",
	ElTableColumn: "el-table-column",
	ElTree: "el-tree",
	ElTreeSelect: "el-tree-select",
	ElUpload: "el-upload",
};

const normalizeMemberName = (name: string, camelCase = false): string => {
	const normalizedName = name.replace(/^\[(.+)\]$/, "$1");
	return camelCase ? normalizedName.replace(/-([a-z])/g, (_, character: string) => character.toUpperCase()) : normalizedName;
};

const normalizeMemberType = (type: unknown): string | undefined => {
	if (!type) return undefined;
	if (typeof type === "string") return type;
	if (!Array.isArray(type)) return undefined;
	return (type as unknown[])
		.map((item) => {
			if (typeof item === "string") return item;
			if (item && typeof item === "object") {
				const itemName = (item as Record<string, unknown>)["name"];
				if (typeof itemName === "string") return itemName;
			}
			return "unknown";
		})
		.join(" / ");
};

const normalizeMemberDescription = (description: string | undefined): string | undefined =>
	description
		?.replace(/\[([^\]]+)\]\([^)]+\)/g, "$1")
		.replaceAll("`", "")
		.replaceAll(/\s+/g, " ")
		.trim();

const normalizeMembers = (members: ElementPlusWebTypeMember[] | undefined, camelCase = false): NativeApiMember[] =>
	(members ?? []).map((item) => ({
		name: normalizeMemberName(item.name, camelCase),
		description: normalizeMemberDescription(item.description),
		type: normalizeMemberType(item.type),
	}));

const webTypeComponents = (elementPlusWebTypes as ElementPlusWebTypes).contributions.html["vue-components"];

export const nativeDocumentation = Object.fromEntries(
	Object.entries(nativeTagNames).map(([componentName, tagName]) => {
		const component = webTypeComponents.find((item) => item.name === tagName);
		return [
			componentName,
			{
				props: normalizeMembers(component?.props, true),
				events: normalizeMembers(component?.js?.events),
				slots: normalizeMembers(component?.slots),
			},
		];
	})
) as Record<NativeComponentName, NativeApiDocumentation>;

const selectorSlots = ["default", "header", "footer", "prefix", "empty", "tag", "loading", "label"];
const selectorExposes = ["focus", "blur", "selectedLabel", "loading", "refresh", "setSelection", "clearSelection"];
const uploadExposes = ["abort", "submit", "clearFiles", "handleStart", "handleRemove", "loading", "fileList"];

export const fastMetadata: Record<FastComponentName, ComponentApiMetadata> = {
	FaAvatar: { changedProps: ["icon", "src"], slots: ["default({ src })"], exposes: ["src"] },
	FaButton: {
		changedProps: ["loading", "loadingIcon"],
		slots: ["default", "loading", "icon"],
		exposes: ["ref", "size", "type", "disabled", "shouldAddSpace", "loading", "doLoading(function)"],
	},
	FaCarNumber: {
		changedProps: ["modelValue", "parser", "placeholder", "readonly", "formatter"],
		note: "基于 ElInput 组合车牌键盘；除表中列出的 Input Props 外，不透传 ElInput 插槽和 Expose。",
	},
	FaContextMenu: { exposes: ["visible", "open({ x, y })", "close()"] },
	FaDialog: {
		changedProps: ["alignCenter", "appendToBody", "beforeClose", "destroyOnClose", "draggable", "modelValue", "overflow", "top", "width"],
		slots: ["default({ loading })", "header({ loading, close })", "title", "footer({ loading, close })"],
		exposes: ["handleClose", "dialogContentRef", "resetPosition", "loading", "visible", "open", "close", "refresh", "doLoading"],
	},
	FaDrawer: {
		changedProps: ["appendToBody", "beforeClose", "destroyOnClose", "draggable", "modelValue", "resizable"],
		slots: ["default({ loading })", "header({ loading, close })", "title", "footer({ loading, close })"],
		exposes: ["handleClose", "loading", "visible", "open", "close", "refresh", "doLoading"],
	},
	FaForm: {
		changedProps: ["labelWidth", "labelSuffix", "scrollToError"],
		slots: ["default"],
		exposes: [
			"validate",
			"validateField",
			"resetFields",
			"clearValidate",
			"scrollToField",
			"fields",
			"getField",
			"setInitialValues",
			"validateScrollToField",
		],
	},
	FaFormItem: {
		slots: ["default", "label({ label })", "error({ error })"],
		exposes: ["size", "validateMessage", "validateState", "validate", "clearValidate", "resetField", "setInitialValue"],
	},
	FaFormItemTip: { slots: ["label"] },
	FaIcon: { note: "按 name 前缀解析 Element Plus、Fast、本地图标类名或外部 SVG URL。" },
	FaIconSelector: { exposes: ["iconType", "value"] },
	FaImage: {
		changedProps: ["hideOnClickModal", "lazy", "previewSrcList", "previewTeleported", "src"],
		slots: ["placeholder", "error", "viewer({ src })", "progress", "toolbar", "viewer-error"],
		exposes: ["showPreview"],
	},
	FaInputDialogPage: { slots: ["default（FaTableColumn）"], exposes: ["selectionRow", "open", "clear"] },
	FaLayoutGrid: { slots: ["default"], exposes: ["breakPoint"] },
	FaLayoutGridItem: { slots: ["default"], exposes: ["show"] },
	FaSelect: { changedProps: ["loading", "modelValue", "popperClass", "props"], slots: selectorSlots, exposes: selectorExposes },
	FaSelectOption: { slots: ["default(option)"] },
	FaSelectPage: {
		changedProps: ["loading", "modelValue", "popperClass", "props", "remote"],
		slots: selectorSlots,
		exposes: [...selectorExposes, "selectedList"],
	},
	FaSelectV2: {
		changedProps: ["itemHeight", "loading", "modelValue", "options", "popperClass", "props"],
		slots: selectorSlots,
		exposes: [...selectorExposes, "scrollTo"],
	},
	FaTable: {
		changedProps: ["data", "height", "rowKey", "size"],
		slots: [
			"default",
			"append",
			"empty",
			"topHeader",
			"header",
			"toolButton",
			"toolButtonAdv",
			"operation",
			"pagination",
			"footer",
			"columnSetting",
			"动态命名列/搜索插槽",
		],
		exposes: [
			"clearSelection",
			"getSelectionRows",
			"getHalfSelectionRows",
			"toggleRowSelection",
			"toggleAllSelection",
			"toggleRowExpansion",
			"setCurrentRow",
			"clearSort",
			"clearFilter",
			"doLayout",
			"sort",
			"scrollTo",
			"setScrollTop",
			"setScrollLeft",
			"columns",
			"updateKeyChildren",
			"loading",
			"tableData",
			"tablePagination",
			"searchParam",
			"selected",
			"selectedList",
			"selectedListIds",
			"indeterminateSelectedListIds",
			"tableWidth",
			"tableHeight",
			"toggleRowIndeterminateSelection",
			"refresh",
			"reset",
			"doRender",
			"doLoading",
		],
	},
	FaTableColumn: { changedProps: ["type"], slots: ["default(scope)", "header(scope)"] },
	FaTableColumnsSettingDialog: { exposes: ["open", "change"] },
	FaTablePagination: {},
	FaTableSearchForm: { slots: ["动态命名列/搜索插槽"] },
	FaTableSearchFormItem: { slots: ["动态命名列/搜索插槽"] },
	FaTree: {
		changedProps: ["data", "filterNodeMethod", "nodeKey", "props"],
		slots: ["default({ node, data })", "label({ node, data })", "empty"],
		exposes: [
			"filter",
			"getNodeKey",
			"getNodePath",
			"updateKeyChildren",
			"getCheckedNodes",
			"setCheckedNodes",
			"getCheckedKeys",
			"setCheckedKeys",
			"setChecked",
			"getHalfCheckedNodes",
			"getHalfCheckedKeys",
			"getCurrentKey",
			"getCurrentNode",
			"setCurrentKey",
			"setCurrentNode",
			"getNode",
			"remove",
			"append",
			"insertBefore",
			"insertAfter",
			"loading",
			"refresh",
		],
	},
	FaTreeSelect: {
		changedProps: ["data", "filterNodeMethod", "loading", "modelValue", "props"],
		slots: selectorSlots,
		exposes: [
			"focus",
			"blur",
			"selectedLabel",
			"filter",
			"updateKeyChildren",
			"getCheckedNodes",
			"setCheckedNodes",
			"getCheckedKeys",
			"setCheckedKeys",
			"setChecked",
			"getHalfCheckedNodes",
			"getHalfCheckedKeys",
			"getCurrentKey",
			"getCurrentNode",
			"setCurrentKey",
			"setCurrentNode",
			"getNode",
			"remove",
			"append",
			"insertBefore",
			"insertAfter",
			"treeRef",
			"selectRef",
			"loading",
			"refresh",
			"setSelection",
			"clearSelection",
		],
	},
	FaUpload: {
		changedProps: ["beforeUpload", "fileList", "httpRequest", "method"],
		slots: ["default", "trigger", "tip", "file"],
		exposes: uploadExposes,
	},
	FaUploadImage: {
		changedProps: ["accept", "beforeUpload", "fileList", "httpRequest", "limit", "listType", "method", "showFileList"],
		slots: ["default"],
		exposes: [...uploadExposes, "preview", "previewList"],
	},
	FaUploadImages: {
		changedProps: ["accept", "beforeUpload", "fileList", "httpRequest", "limit", "listType", "method", "multiple"],
		slots: ["default"],
		exposes: [...uploadExposes, "preview", "previewList"],
	},
};

export const nativeMetadata: Record<NativeComponentName, ComponentApiMetadata> = {
	ElAvatar: { slots: ["default"] },
	ElButton: { slots: ["default", "loading", "icon"], exposes: ["ref", "size", "type", "disabled", "shouldAddSpace"] },
	ElDialog: { slots: ["default", "header", "footer"], exposes: ["handleClose", "dialogContentRef", "resetPosition"] },
	ElDrawer: { slots: ["default", "header", "footer"], exposes: ["handleClose"] },
	ElForm: {
		slots: ["default"],
		exposes: ["validate", "validateField", "resetFields", "clearValidate", "scrollToField", "fields", "getField", "setInitialValues"],
	},
	ElFormItem: {
		slots: ["default", "label", "error"],
		exposes: ["size", "validateMessage", "validateState", "validate", "clearValidate", "resetField", "setInitialValue"],
	},
	ElIcon: { slots: ["default"] },
	ElImage: { slots: ["placeholder", "error", "viewer", "progress", "toolbar", "viewer-error"], exposes: ["showPreview"] },
	ElInput: {
		slots: ["prefix", "suffix", "prepend", "append"],
		exposes: ["input", "textarea", "ref", "textareaStyle", "autosize", "focus", "blur", "select", "clear", "resizeTextarea"],
	},
	ElOption: { slots: ["default"] },
	ElSelect: {
		slots: selectorSlots,
		exposes: ["focus", "blur", "selectedLabel", "scrollTo", "handleClose"],
	},
	ElSelectV2: {
		slots: selectorSlots,
		exposes: ["focus", "blur", "scrollTo", "resetScrollTop", "selectedLabel"],
	},
	ElTable: {
		slots: ["default", "append", "empty"],
		exposes: [
			"clearSelection",
			"getSelectionRows",
			"toggleRowSelection",
			"toggleAllSelection",
			"toggleRowExpansion",
			"setCurrentRow",
			"clearSort",
			"clearFilter",
			"doLayout",
			"sort",
			"scrollTo",
			"setScrollTop",
			"setScrollLeft",
			"columns",
			"updateKeyChildren",
		],
	},
	ElTableColumn: { slots: ["default", "header", "filter-icon"] },
	ElTree: {
		slots: ["default", "empty"],
		exposes: fastMetadata.FaTree.exposes?.filter((name) => !["loading", "refresh"].includes(name)),
	},
	ElTreeSelect: {
		slots: selectorSlots,
		exposes: ["treeRef", "selectRef", "filter", "focus", "blur"],
	},
	ElUpload: { slots: ["default", "trigger", "tip", "file"], exposes: ["abort", "submit", "clearFiles", "handleStart", "handleRemove"] },
};

export const propDescriptions: Record<string, string> = {
	_children: "多级表头的子列配置。",
	accept: "允许选择的文件类型，格式与原生 input accept 属性一致。",
	action: "上传请求地址。",
	afterOpen: "Fast 打开业务钩子，支持异步函数。",
	advancedSearchDrawer: "是否在 Drawer 中展示高级搜索条件。",
	alignCenter: "是否让 Dialog 在页面中垂直居中。",
	allowCreate: "是否允许创建新选项。",
	allValue: "树组件“全部”节点对应的绑定值。",
	appendTo: "浮层挂载目标。",
	appendToBody: "是否挂载到 body。",
	autoRefresh: "是否按配置自动刷新。",
	autoUpload: "选择文件后是否立即上传。",
	base64: "将值作为 Base64 图片内容。",
	beforeClose: "关闭前回调。",
	beforeRemove: "移除上传文件前的回调。",
	beforeUpload: "上传前的校验回调。",
	border: "是否显示表格边框。",
	checkStrictly: "父子节点的选中状态是否互不关联。",
	clearable: "是否允许清空。",
	collapseTags: "多选时是否折叠标签。",
	collapseTagsTooltip: "是否以 Tooltip 展示折叠标签。",
	collapsed: "是否启用折叠布局计算。",
	collapsedRows: "折叠状态保留的行数。",
	cols: "各响应式断点的列数。",
	columns: "表格列配置。",
	columnsChange: "列设置变化回调。",
	columnSettingBtn: "是否显示列设置按钮。",
	copy: "是否显示单元格复制操作。",
	closeButtonText: "底部关闭按钮文本。",
	collapseOnClickNode: "点击树节点后是否自动收起同级展开节点。",
	collapsedSearch: "是否默认折叠表格搜索条件。",
	confirmButtonText: "底部确认按钮文本。",
	customIcons: "追加到图标选择器中的自定义图标名称列表。",
	data: "组件数据。",
	dataCallback: "表格请求数据完成后的转换或回调函数。",
	dataDeleteField: "标记逻辑删除状态的字段名，命中后单元格显示删除遮罩。",
	dataSearchRange: "表格默认时间搜索范围。",
	dateFix: "日期列是否同时显示相对时间标签。",
	dateFormat: "日期列的自定义格式化模板。",
	defaultExpandAll: "是否默认展开全部节点。",
	defaultSelection: "树组件初始化时默认选中的节点值。",
	defaultSelected: "是否根据当前值初始化选中项。",
	detailForm: "是否启用详情表单样式。",
	destroyOnClose: "关闭后是否销毁弹层内容。",
	disabled: "是否禁用组件或当前选项。",
	disabledConfirmButton: "是否禁用 Fast 底部确认按钮。",
	disabledLoading: "点击时不启用 Fast 自动 Loading。",
	draggable: "是否允许拖动。",
	emptyText: "空数据提示文字。",
	filterable: "是否允许筛选。",
	filterNodeMethod: "树节点过滤函数，返回 false 时隐藏当前节点。",
	fit: "内容如何适应容器。",
	formatter: "显示值格式化函数。",
	fileList: "上传文件列表的双向绑定值。",
	fullHeight: "Dialog 内容是否占满可用高度。",
	futureSearchTime: "时间搜索是否允许选择未来日期。",
	gap: "网格水平与垂直间距。",
	grid: "是否使用 Fast 响应式网格。",
	hamburger: "是否显示树的折叠控制。",
	headers: "上传请求头。",
	height: "组件高度。",
	headerCard: "表格头部是否使用卡片容器样式。",
	headerRender: "使用 TSX 自定义表格列头的渲染函数。",
	headerSlot: "自定义表格列头使用的命名插槽。",
	hideAll: "是否隐藏树的全部节点。",
	hideFilter: "是否隐藏树过滤输入框。",
	hideFooter: "是否隐藏底部操作区。",
	hideOnClickModal: "点击图片预览遮罩时是否关闭预览。",
	hideImage: "是否隐藏图片列预览。",
	hideSearchTime: "是否隐藏默认时间搜索项。",
	httpRequest: "自定义上传请求实现，优先级最高。",
	initParam: "请求初始化参数。",
	itemHeight: "虚拟列表选项高度。",
	icon: "图标组件或图标名称。",
	label: "显示文本或同步标签值。",
	labelSuffix: "表单标签统一后缀。",
	labelWidth: "表单标签宽度。",
	labelKey: "选中行的标签字段。",
	lazy: "是否启用懒加载。",
	limit: "允许上传或选择的最大数量。",
	link: "将表格单元格显示为链接。",
	listType: "上传文件列表样式。",
	loading: "加载状态。",
	loadingIcon: "加载状态显示的图标组件。",
	lg: "lg 断点下的布局配置。",
	maxSize: "文件大小上限，单位 KB。",
	method: "上传 HTTP 方法。",
	modelValue: "v-model 绑定值。",
	md: "md 断点下的布局配置。",
	moreDetail: "是否启用更宽的选项详情布局。",
	multiple: "是否允许多选。",
	nodeKey: "树节点唯一键。",
	name: "图标名称、CSS 类名或外部 SVG 地址。",
	normal: "使用标准图地址后缀。",
	original: "使用原始图片地址。",
	offset: "偏移量或浮层偏移。",
	options: "虚拟选择器的选项数据。",
	overflow: "拖动 Dialog 时是否允许超出可视区域。",
	pageResult: "分页数据。",
	pageSizes: "分页可选每页数量。",
	pagination: "是否显示分页或分页配置。",
	placeholder: "占位提示。",
	parser: "输入值解析函数，在写入模型前转换显示文本。",
	popperClass: "下拉浮层的自定义类名。",
	preview: "是否允许图片预览。",
	previewSrcList: "图片预览列表。",
	previewTeleported: "图片预览层是否挂载到 body。",
	props: "字段映射配置。",
	refreshBtn: "是否显示刷新按钮。",
	requestApi: "异步数据请求函数。",
	readonly: "是否以只读方式展示输入值。",
	remote: "是否启用远程搜索模式。",
	render: "使用 TSX 自定义表格单元格的渲染函数。",
	resizable: "是否允许调整 Drawer 尺寸。",
	row: "是否独占一整行。",
	rowClickSelection: "点击行时是否切换选择。",
	rowKey: "行或节点唯一键。",
	rowSelectable: "判断表格行是否允许选择的函数。",
	searchBtn: "是否显示搜索按钮。",
	searchForm: "搜索表单初始值。",
	searchFormCols: "搜索表单响应式列数。",
	showBeforeClose: "是否在关闭前显示团队确认提示。",
	showCloseButton: "是否显示底部关闭按钮。",
	showConfirmButton: "是否显示底部确认按钮。",
	showFileList: "是否显示文件列表。",
	showFullscreen: "是否显示全屏按钮。",
	showRefresh: "是否显示刷新按钮。",
	single: "是否使用单选表格模式。",
	size: "组件尺寸。",
	slot: "自定义表格单元格使用的命名插槽。",
	small: "使用小图地址后缀。",
	smallWidth: "小尺寸模式下的表格列宽度。",
	sm: "sm 断点下的布局配置。",
	span: "占用的网格列数。",
	spanProp: "计算表格纵向合并行时使用的字段名。",
	src: "图片地址或 Base64 图片内容。",
	stripe: "是否显示斑马纹。",
	show: "是否显示当前表格列或布局项。",
	scrollToError: "校验失败时是否滚动到首个错误字段。",
	suffix: "是否作为布局末尾操作项。",
	tag: "是否将单元格显示为标签。",
	tableKey: "表格实例及持久化配置使用的唯一标识。",
	timeInfoField: "时间信息列中用户名和时间字段的映射。",
	title: "组件标题文本。",
	top: "Dialog 距离页面顶部的偏移。",
	thumb: "使用缩略图地址后缀。",
	tips: "标签提示内容。",
	toolBtn: "是否显示表格工具按钮区域。",
	treeData: "将每个父项的 children 展开为表格行，并把父项字段合并到子项；Element Plus 树表展开无需启用。",
	value: "选项绑定值；显式传入时优先于 data 字段映射。",
	children: "选项分组的子选项数据。",
	click: "链接列点击回调，参数包含当前行和行索引。",
	clickEmit: "链接列点击时触发的自定义事件名称。",
	originalImage: "图片列是否使用原图地址进行展示和预览。",
	enum: "枚举字典、字典名称或按行返回字典的函数。",
	autoWidth: "是否根据单元格内容自动计算表格列宽。",
	uploadApi: "Fast 上传函数。",
	uploadUrl: "Fast 内置上传请求地址。",
	accordion: "是否每次只展开一个同级树节点。",
	allowDrag: "判断指定树节点是否允许被拖动。",
	allowDrop: "判断拖动节点是否允许放置到目标位置。",
	ariaLabel: "组件面向辅助技术的可访问名称。",
	ariaLevel: "弹层标题在可访问性树中的标题层级。",
	autoExpandParent: "展开节点时是否自动展开其父节点。",
	autocomplete: "输入框原生 autocomplete 属性。",
	automaticDropdown: "获得焦点后是否自动打开下拉菜单。",
	cacheData: "懒加载场景中用于补全选中标签的缓存节点数据。",
	center: "是否让 Dialog 头部和底部内容水平居中。",
	checkDescendants: "懒加载节点时是否选中已选父节点的后代节点。",
	checkOnClickLeaf: "点击树叶子节点时是否切换勾选状态。",
	checkOnClickNode: "点击树节点时是否切换勾选状态。",
	className: "表格单元格或表头单元格的自定义类名。",
	clearIcon: "清空按钮使用的图标组件。",
	closeIcon: "关闭按钮使用的图标组件。",
	containerRole: "输入组合容器的 ARIA role。",
	currentNodeKey: "初始化时设为当前节点的 key。",
	debounce: "远程搜索输入的防抖时间，单位毫秒。",
	defaultCheckedKeys: "初始化时默认勾选的节点 key 集合。",
	defaultExpandedKeys: "初始化时默认展开的节点 key 集合。",
	defaultFirstOption: "按 Enter 时是否默认选择首个匹配选项。",
	effect: "下拉浮层使用的 Tooltip 主题。",
	emptyValues: "视为空值的模型值集合。",
	expandOnClickNode: "点击树节点内容时是否展开或收起节点。",
	fallbackPlacements: "首选位置空间不足时依次尝试的浮层位置。",
	filterMethod: "本地筛选选项时调用的过滤函数。",
	fitInputWidth: "下拉浮层宽度是否至少与输入框一致。",
	fullscreen: "是否让 Dialog 占满可视区域。",
	highlightCurrent: "是否高亮显示树的当前节点。",
	id: "组件根输入元素的原生 id。",
	indent: "相邻树层级之间的水平缩进像素。",
	load: "树节点懒加载函数。",
	loadingText: "远程数据加载期间显示的文字。",
	maxCollapseTags: "折叠多选标签前最多保留的标签数量。",
	modalFade: "Drawer 遮罩层是否使用淡入淡出动画。",
	multipleLimit: "多选模式允许选择的最大项目数，0 表示不限制。",
	noDataText: "没有可用选项或树节点时显示的文字。",
	noMatchText: "筛选没有匹配结果时显示的文字。",
	persistent: "下拉浮层隐藏后是否保留在 DOM 中。",
	placement: "下拉浮层相对触发元素的首选位置。",
	popperOptions: "传递给 Popper 的定位配置。",
	popperStyle: "下拉浮层根元素的自定义样式。",
	property: "表格列对应的数据字段，语义与 prop 相同。",
	remoteMethod: "远程搜索关键字变化时调用的数据加载函数。",
	remoteShowSuffix: "远程搜索模式下是否显示选择器后缀图标。",
	renderAfterExpand: "是否在树节点首次展开后再渲染其子节点。",
	renderContent: "自定义树节点内容的渲染函数。",
	reserveKeyword: "多选远程搜索选中项目后是否保留关键字。",
	showArrow: "下拉浮层是否显示指向触发元素的箭头。",
	showCheckbox: "是否在树节点前显示复选框。",
	style: "表格单元格或表头单元格的自定义样式。",
	suffixIcon: "选择器右侧显示的后缀图标组件。",
	tabindex: "组件输入元素的原生 tabindex。",
	tagEffect: "多选标签使用的 Element Plus 主题效果。",
	tagTooltip: "折叠标签 Tooltip 的自定义配置。",
	tagType: "多选标签使用的 Element Plus 类型。",
	teleported: "是否将下拉浮层传送到 appendTo 指定的容器。",
	transition: "弹层打开和关闭使用的过渡名称。",
	trapFocus: "弹层打开时是否将键盘焦点限制在弹层内部。",
	validateEvent: "模型值变化时是否触发表单校验。",
	valueKey: "选项值为对象时用于唯一标识选项的字段名。",
	valueOnClear: "清空时写入模型的值或值生成函数。",
	width: "组件宽度。",
	xl: "xl 断点下的布局配置。",
	xs: "xs 断点下的布局配置。",
};

export const componentPropDescriptions: Record<string, Record<string, string>> = {
	ElAvatar: {
		alt: "图片加载失败时的替代文本。",
		fit: "头像图片的裁剪适应方式。",
		icon: "没有图片时显示的图标。",
		shape: "头像形状。",
		src: "头像图片地址。",
		srcSet: "原生图片 srcset 属性。",
	},
	ElButton: {
		autoInsertSpace: "是否在两个中文字符之间自动插入空格。",
		autofocus: "是否自动获取焦点。",
		bg: "文字按钮是否显示背景。",
		circle: "是否显示为圆形按钮。",
		color: "按钮自定义颜色。",
		dark: "自定义颜色是否使用暗色模式。",
		dashed: "是否显示为虚线按钮。",
		disabled: "是否禁用按钮。",
		icon: "按钮图标。",
		link: "是否显示为链接按钮。",
		loading: "是否显示加载状态。",
		loadingIcon: "加载状态使用的图标。",
		nativeType: "按钮原生 type 属性。",
		plain: "是否显示为朴素按钮。",
		round: "是否显示为圆角按钮。",
		tag: "按钮渲染使用的 HTML 标签或组件。",
		text: "是否显示为文字按钮。",
		type: "按钮视觉类型。",
	},
	ElForm: { model: "表单数据对象。", rules: "表单校验规则。" },
	ElImage: { fit: "图片在容器内的适应方式。", src: "图片地址。" },
	ElInput: { type: "输入框原生类型。" },
	ElSelect: { options: "通过属性直接传入的选项。", props: "options 字段别名配置。" },
	ElSelectV2: { data: "虚拟列表选项数据。", height: "虚拟下拉列表高度。", options: "虚拟列表选项数据。", props: "选项字段别名配置。" },
	ElTable: { data: "表格行数据。", fit: "列宽是否自动撑满表格容器。", height: "表格固定高度。" },
	ElTableColumn: { type: "列类型：default、selection、index 或 expand。" },
	ElTree: { data: "树节点数据。", props: "树节点字段别名配置。" },
	ElTreeSelect: { data: "树选择节点数据。", props: "树节点字段别名配置。" },
	ElUpload: { data: "附加到上传请求的表单字段。", name: "上传文件的表单字段名。" },
	FaTableColumn: { link: "将单元格显示为链接按钮。", tag: "将单元格显示为枚举标签。", type: "Fast 业务列类型。" },
	FaTableColumnsSettingDialog: { change: "列配置发生变化后调用的保存回调。" },
	FaTableSearchForm: { reset: "重置表格搜索条件的异步函数。", search: "执行表格搜索的异步函数。" },
	FaTableSearchFormItem: { column: "当前搜索项对应的 FaTable 列配置。", search: "当前搜索值变化后执行的异步搜索函数。" },
};

export const eventDescriptions: Record<string, string> = {
	"update:modelValue": "更新 v-model。",
	"update:label": "更新标签绑定值。",
	"update:fileList": "更新上传文件列表。",
	"break-point-change": "容器宽度跨越响应式断点时触发，参数为新的断点名称。",
	breakPointChange: "容器宽度跨越响应式断点时触发，参数为新的断点名称。",
	"cell-click": "点击单元格时触发，参数与 ElTable cell-click 一致。",
	"cell-contextmenu": "右键点击单元格时触发。",
	"cell-dblclick": "双击单元格时触发。",
	"cell-mouse-enter": "鼠标进入单元格时触发。",
	"cell-mouse-leave": "鼠标离开单元格时触发。",
	"check-change": "树节点选中状态变化时触发。",
	"close-auto-focus": "弹层关闭并完成焦点恢复时触发。",
	"current-change": "表格当前行、树当前节点或选择值变化时触发。",
	"end-reached": "选择器滚动到下拉列表边界时触发。",
	"expand-change": "表格行展开状态变化时触发。",
	"filter-change": "表格筛选条件变化时触发。",
	"header-click": "点击表头单元格时触发。",
	"header-contextmenu": "右键点击表头单元格时触发。",
	"header-dragend": "拖动表头改变列宽结束时触发。",
	"node-click": "点击树节点时触发。",
	"node-collapse": "树节点收起时触发。",
	"node-contextmenu": "右键点击树节点时触发。",
	"node-drag-end": "树节点拖动结束时触发。",
	"node-drag-enter": "拖动节点进入目标节点时触发。",
	"node-drag-leave": "拖动节点离开目标节点时触发。",
	"node-drag-over": "拖动节点经过目标节点时触发。",
	"node-drag-start": "开始拖动树节点时触发。",
	"node-drop": "树节点完成放置时触发。",
	"node-expand": "树节点展开时触发。",
	"open-auto-focus": "弹层打开并完成自动聚焦时触发。",
	"popup-scroll": "选择器下拉列表滚动时触发。",
	"remove-tag": "多选模式移除标签时触发，参数为被移除的值。",
	"resize-end": "Drawer 拖动调整尺寸结束时触发。",
	"resize-start": "Drawer 开始拖动调整尺寸时触发。",
	"row-click": "点击表格行时触发。",
	"row-contextmenu": "右键点击表格行时触发。",
	"row-dblclick": "双击表格行时触发。",
	"sort-change": "表格排序条件变化时触发。",
	"visible-change": "选择器下拉浮层显示状态变化时触发。",
	blur: "组件失去焦点时触发。",
	cellClick: "点击单元格时触发，参数为行、列、单元格和原生事件。",
	cellContextmenu: "右键点击单元格时触发。",
	cellDblclick: "双击单元格时触发。",
	cellMouseEnter: "鼠标进入单元格时触发。",
	cellMouseLeave: "鼠标离开单元格时触发。",
	change: "值或选择发生变化。",
	check: "点击树节点复选框后触发，参数包含节点数据和选中集合。",
	click: "点击时触发。",
	clear: "点击清空按钮并完成清空时触发。",
	close: "关闭流程完成时触发。",
	closeAutoFocus: "弹层关闭并完成焦点恢复时触发。",
	closed: "关闭动画完成时触发。",
	confirmClick: "点击 Fast 确认按钮时触发。",
	customCellClick: "点击 Fast 链接列时触发，参数为自定义事件名和当前单元格上下文。",
	currentChange: "表格当前行、树当前节点或选择值变化时触发。",
	dataChangeCallBack: "异步数据加载完成时触发。",
	endReached: "选择器滚动到下拉列表边界时触发。",
	error: "资源加载或组件处理失败时触发。",
	expandChange: "表格行展开状态变化时触发。",
	filterChange: "表格筛选条件变化时触发。",
	focus: "组件获得焦点时触发。",
	headerClick: "点击表头单元格时触发。",
	headerContextmenu: "右键点击表头单元格时触发。",
	headerDragend: "拖动表头改变列宽结束时触发。",
	imagePreview: "打开图片预览时触发，参数为图片地址。",
	load: "资源加载成功时触发。",
	open: "Fast 打开业务流程完成时触发。",
	openAutoFocus: "弹层打开并完成自动聚焦时触发。",
	opened: "打开动画完成时触发。",
	paginationChange: "表格页码或每页条数变化时触发。",
	popupScroll: "选择器下拉列表滚动时触发。",
	refresh: "刷新数据时触发。",
	removeTag: "多选模式移除标签时触发，参数为被移除的值。",
	reset: "重置搜索条件时触发。",
	resize: "Drawer 拖动过程中尺寸变化时持续触发。",
	rowClick: "点击表格行时触发，参数与 ElTable row-click 一致。",
	rowContextmenu: "右键点击表格行时触发。",
	rowDblclick: "双击表格行时触发。",
	scroll: "表格或选择器滚动时触发。",
	select: "选择行或选项时触发。",
	selectAll: "表格全选状态变化时触发，参数为当前选择行。",
	selectionChange: "表格选择集合变化时触发。",
	show: "图片预览器显示时触发。",
	sizeChange: "表格每页条数变化时触发。",
	sortChange: "表格排序条件变化时触发。",
	switch: "图片预览器切换当前图片时触发。",
	validate: "表单项校验后触发。",
	visibleChange: "选择器下拉浮层显示状态变化时触发。",
};

export const slotDescriptions: Record<string, string> = {
	append: "在表格最后一行之后追加自定义内容。",
	columnSetting: "自定义表格列设置区域。",
	default: "组件默认内容插槽。",
	"default(scope)": "自定义表格单元格内容，参数包含行、列和行索引。",
	"default（FaTableColumn）": "声明弹窗选择表格使用的 FaTableColumn。",
	"动态命名列/搜索插槽": "按列 slot、headerSlot 或搜索字段名动态生成的业务插槽。",
	empty: "组件无数据时的自定义内容。",
	error: "表单校验错误或图片加载失败时的自定义内容。",
	file: "自定义上传文件条目内容。",
	footer: "自定义底部操作区域；弹层中可获得 loading 和 close。",
	header: "自定义头部内容或表格头部业务区域。",
	"header(scope)": "自定义表格列头，参数包含列和列索引。",
	icon: "自定义按钮或组件图标。",
	label: "自定义表单标签、树节点标签或选择项标签。",
	loading: "自定义加载状态内容。",
	operation: "自定义表格操作列内容。",
	pagination: "自定义表格分页区域。",
	placeholder: "图片加载过程中的占位内容。",
	prefix: "自定义选择器输入框前缀内容。",
	progress: "自定义图片加载进度内容。",
	tag: "自定义多选标签内容。",
	tip: "自定义上传提示说明。",
	title: "自定义 Dialog 或 Drawer 标题。",
	toolbar: "自定义图片预览工具栏。",
	toolButton: "自定义表格常用工具按钮区域。",
	toolButtonAdv: "自定义表格高级工具按钮区域。",
	topHeader: "自定义表格最顶部内容。",
	trigger: "自定义打开文件选择器的触发内容。",
	viewer: "自定义图片预览器内容。",
	"viewer-error": "图片预览器加载失败时的自定义内容。",
};

export const exposeDescriptions: Record<string, string> = {
	abort: "中止指定文件或全部文件的上传请求。",
	append: "向树中追加一个子节点。",
	autosize: "当前输入框的自动高度配置。",
	blur: "让输入或选择组件失去焦点。",
	breakPoint: "当前容器命中的响应式断点。",
	clear: "清空当前选择值。",
	clearFiles: "清空上传文件列表，可指定文件状态。",
	clearFilter: "清除表格列筛选条件。",
	clearSelection: "清除当前选择集合。",
	clearSort: "清除表格排序状态。",
	clearValidate: "清除一个或多个表单字段的校验状态。",
	close: "执行 Fast 异步关闭流程。",
	columns: "ElTable 当前渲染的列上下文集合。",
	dialogContentRef: "ElDialog 内部内容组件引用。",
	disabled: "按钮当前是否处于禁用状态。",
	doLayout: "重新计算表格布局。",
	doLoading: "在统一 Loading 和遮罩状态下执行同步或异步函数。",
	doRender: "强制重新计算并渲染表格内容。",
	fields: "当前注册到表单中的字段上下文集合。",
	fileList: "当前上传文件列表。",
	filter: "按关键字执行树节点过滤。",
	focus: "让输入或选择组件获得焦点。",
	getCheckedKeys: "获取树中已勾选节点的 key 集合。",
	getCheckedNodes: "获取树中已勾选节点的数据集合。",
	getCurrentKey: "获取树当前节点的 key。",
	getCurrentNode: "获取树当前节点数据。",
	getField: "按 prop 获取指定表单字段上下文。",
	getHalfCheckedKeys: "获取树中半选节点的 key 集合。",
	getHalfCheckedNodes: "获取树中半选节点的数据集合。",
	getHalfSelectionRows: "获取树形表格中处于半选状态的行。",
	getNode: "按数据或 key 获取树节点实例。",
	getNodeKey: "获取指定树节点的唯一 key。",
	getNodePath: "获取从根节点到指定节点的数据路径。",
	getSelectionRows: "获取表格当前选中的行。",
	handleClose: "调用 Element Plus 内部关闭处理。",
	handleRemove: "从上传列表移除指定文件。",
	handleStart: "将原始文件加入上传队列。",
	iconType: "当前图标选择器使用的图标来源类型。",
	indeterminateSelectedListIds: "树形表格中半选行的主键集合。",
	input: "ElInput 内部 input 元素引用。",
	insertAfter: "在指定树节点之后插入节点。",
	insertBefore: "在指定树节点之前插入节点。",
	loading: "Fast 业务加载状态。",
	open: "执行 Fast 异步打开流程。",
	preview: "打开指定上传图片的预览。",
	previewList: "当前可预览图片地址列表。",
	ref: "底层 Element Plus 组件引用。",
	refresh: "重新执行组件数据请求或刷新业务内容。",
	remove: "从树中移除指定节点。",
	reset: "重置表格搜索条件、分页和数据。",
	resetField: "将表单字段重置为初始值并清除校验。",
	resetFields: "将整个表单或指定字段重置为初始值并清除校验。",
	resetPosition: "将 Dialog 恢复到初始位置。",
	resetScrollTop: "将虚拟选择器滚动位置重置到顶部。",
	resizeTextarea: "重新计算 textarea 高度。",
	scrollTo: "滚动表格或虚拟列表到指定位置。",
	scrollToField: "滚动到指定表单字段。",
	searchParam: "表格当前提交给请求函数的搜索参数。",
	select: "选中 ElInput 中的全部文本。",
	selected: "表格是否存在选中行。",
	selectedLabel: "选择器当前显示的标签文本。",
	selectedList: "当前选中的完整数据对象集合。",
	selectedListIds: "当前选中行的主键集合。",
	selectionRow: "弹窗分页选择器当前选中的行。",
	selectRef: "FaTreeSelect 内部 ElSelect 引用。",
	setChecked: "设置指定树节点的勾选状态。",
	setCheckedKeys: "按 key 集合设置树勾选状态。",
	setCheckedNodes: "按节点数据集合设置树勾选状态。",
	setCurrentKey: "按 key 设置树当前节点。",
	setCurrentNode: "按节点数据设置树当前节点。",
	setInitialValue: "更新单个表单字段的初始值。",
	setInitialValues: "批量更新表单字段的初始值。",
	setCurrentRow: "设置表格当前高亮行。",
	setScrollLeft: "设置表格横向滚动位置。",
	setScrollTop: "设置表格纵向滚动位置。",
	setSelection: "设置选择器的选中值及标签。",
	shouldAddSpace: "按钮是否会在两个中文字符之间自动插入空格。",
	show: "布局项当前是否可见。",
	showPreview: "打开 ElImage 图片预览器。",
	size: "按钮解析后的实际尺寸。",
	sort: "按指定列和顺序执行表格排序。",
	src: "FaAvatar 处理后的最终图片地址。",
	submit: "手动提交处于 ready 状态的上传文件。",
	tableData: "表格当前渲染的数据集合。",
	tableHeight: "表格计算后的可用高度。",
	tablePagination: "表格当前分页状态。",
	tableWidth: "表格计算后的可用宽度。",
	textarea: "ElInput 内部 textarea 元素引用。",
	textareaStyle: "ElInput 计算后的 textarea 样式。",
	toggleAllSelection: "切换表格全选状态。",
	toggleRowExpansion: "切换指定表格行的展开状态。",
	toggleRowIndeterminateSelection: "切换树形表格行的半选状态。",
	toggleRowSelection: "切换指定表格行的选中状态。",
	treeRef: "FaTreeSelect 内部 ElTree 引用。",
	type: "按钮解析后的实际类型。",
	updateKeyChildren: "按节点 key 更新树或树形表格的子节点。",
	validate: "校验整个表单。",
	validateField: "校验一个或多个指定字段。",
	validateMessage: "表单项当前校验提示文本。",
	validateScrollToField: "校验表单并滚动到首个错误字段。",
	validateState: "表单项当前校验状态。",
	value: "图标选择器当前绑定值。",
	visible: "弹层或右键菜单当前是否可见。",
};
